### ISSUE TITLE
Some dependencies aren't being fetched

### ISSUE THREAD

**Issue by embedded-creations** [qnxor/macoh#10]
I ran the FFT test and first got this error
```
macoh.sh: line 775: /Applications/Intel Power Gadget/PowerLog: No such file or directory
```
I ran again and selected the option to download the Intel Power Gadget, and Graphics Layout Engine manually.

I ran the FFT test again and got this message at the end
```
See /Users/louis/macoh/20150813-163121-fft.gif for the full graph.

The file /Users/louis/macoh/20150813-163121-fft.gif does not exist.
```
I used Homebrew to install ImageMagick as it wasn't an option for manual install in the menu, ran again, and got the graph I expected.

Next I ran Short x264 encode, and it fetched ImageMagick.  Maybe the FFT test isn't looking for dependencies properly?

**Comment by qnxor** [comment]
You're right, the FFT test was not checking for dependencies. Fixed in the latest commit and release. Thanks for reporting.
