### ISSUE TITLE
Support for Intel Power Gadget 3.03 and Intel Core M pocessors?

### ISSUE THREAD

**Issue by nazgul6** [qnxor/macoh#11]
Hi.

Just wondering if the tool could be updated to support the new Intel Power Gadget 3.03 and with that Intel Core M processors (as in the new retina MacBooks). The 3.03 version of the gadget works fine for tracking Power / Frequency / Temperature of Core M, however, MacOH insists on downloading the old version which did not not support Core M processors.

Really curious about the amount of throttling in Core M vs Core i5 as Geekbench and Cinebench scores are very close.

Thanks,
NazgulRR from Macrumors

**Comment by qnxor** [comment]
Please edit `macoh.conf` and change the `url_ipg` to point to the new url. Specifically:
```
url_ipg="https://software.intel.com/file/501089/download"
```
Post back with your results.

**Comment by nazgul6** [comment]
Worked brilliantly, thanks! Also needed to update the bunny video link (http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_1080p_h264.mov)

Positively surprised by the results (m3-6Y30 1.1GHz base freq):
(all standard length tests)

FFT: average freq 1917mhz, fft/s about 18% less than Core-i5 4250u
x264: average freq 1965mhz and the same fps as the i5-4250u.Virtually no throttling at all for the full 15minutes.
GPU: 28fps (=over double the i5-4250u!), although it (the m3) ran at 685mhz on average (seems low?)

**Comment by qnxor** [comment]
Glad it worked, thanks for reporting.
