### ISSUE TITLE
GPU change isn't reoccuring (gfxCardStatus)

### ISSUE THREAD

**Issue by Archxiao** [qnxor/macoh#9]
Hey @qnxor, the persistence of the script regarding changing the used GPU isn't reoccurring.

In my test, I have changed the GPU to `integrated` and then launched Chromium (which requires the discrete), which is fine, nothing happens. Then, after I close Chromium, the GPU preference goes to `discrete`, and stays.

**Comment by qnxor** [comment]
Hi @Archxiao. First, there is a known bug in gfxCardStatus (see codykrieger/gfxCardStatus/issues/150 and the issues linked to it) which prevents gfxCardStatus from keeping the GPU in the integrated only mode.

Secondly, and more importantly here, the GPU switch feature of my MacOH script was really only meant for the 3D benchmark within MacOH. I have not designed it for other usages outside of MacOH.
